apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-tools
  annotations:
    test-annotation: '{"test-key":"test-value"}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-tools
  template:
    metadata:
      labels:
        app: net-tools
    spec:
      containers:
      - name: net-tools
        image: sjwilliams80/docker-net-tools:latest
        volumeMounts:
        - name: net-tools-pvc
          mountPath: /data
      volumes:
        - name: net-tools-pvc
          persistentVolumeClaim:
            claimName: net-tools-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: net-tools-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp3"
  resources:
    requests:
      storage: 50Gi
